# Generated by Django 2.1.7 on 2019-07-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('delete_time', models.DateTimeField(default=None)),
                ('create_time', models.DateTimeField(default='2019-07-22 10-36-15')),
                ('update_time', models.DateTimeField(default='2019-07-22 10-36-15')),
            ],
            options={
                'db_table': 'web_user',
            },
        ),
    ]
